# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c0e46878dec2e0247ad7f763959865cd906f95a1e382b8793b913f54a6e968765788cfe56a16aad0886cf3e51e2072318eac76927905ea441de5f6c33ec9e06

test:
  secret_key_base: a71bc1a89955cd056481d9aadab7174c45fbf684ee6fbadcbec276832ba6df25e9470d58d1f0ae86468057efa96a44d09f56f94cc7b0045d7f29ad282efdeebe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
